name: Build MokkyBuddy VSCode Plugin

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Mokky Buddy API Build"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Plugin
      - name: Checkout Plugin Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.vscode.mokkybuddy
          token: ${{ secrets.GITHUB_TOKEN }}
          path: plugin

      # Checkout Java App (necessario per leggere il pom.xml)
      - name: Checkout Java App Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.api.mokkybuddy
          ref: main
          token: ${{ secrets.JAVA_APP_PAT }}
          path: app

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Aggiorna versione plugin in base al pom.xml della Java App
      - name: Set plugin version from Java App
        working-directory: plugin
        run: |
          JAVA_VERSION=$(grep -m1 "<version>" ../app/pom.xml | sed -E 's/.*<version>(.*)<\/version>.*/\1/')
          echo "Java App version: $JAVA_VERSION"
          npm version $JAVA_VERSION --no-git-tag-version

      # Commit e push solo se ci sono modifiche
      - name: Commit and push version bump
        working-directory: plugin
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json
          if ! git diff --cached --quiet; then
            git commit -m "Bump plugin version to match Java App [skip ci]"
            git push
          else
            echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build VSCode Plugin
      - name: Build VSCode Plugin
        working-directory: plugin
        run: |
          npm install
          npx vsce package

      # Upload artifact
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mokkybuddy-vscode-plugin
          path: plugin/*.vsix

      # Pubblicazione su Marketplace (opzionale)
      # - name: Publish VSCode Plugin
      #   if: github.ref == 'refs/heads/main'
      #   working-directory: plugin
      #   run: npx vsce publish
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}
