name: Build MokkyBuddy VSCode Plugin

on:
  push:
    branches:
      - main        # build anche al push
  workflow_run:
    workflows: ["Mokky Buddy API Build"]  # build quando finisce la Java App
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
      MAVEN_OPTS: "-Xmx1024m"

    steps:
      # Checkout del plugin VSCode
      - name: Checkout Plugin Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.vscode.mokkybuddy
          path: plugin

      # Checkout della Java App privata (branch main)
      - name: Checkout Java App Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.api.mokkybuddy
          ref: main
          token: ${{ secrets.JAVA_APP_PAT }}
          path: app

      # Setup Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Build Java App
      - name: Build Java App (MokkyBuddy)
        working-directory: app
        run: mvn clean package

      # Copia JAR nel plugin
      - name: Copy JAR to Plugin Resources
        run: |
          mkdir -p plugin/resources
          JAR_FILE=$(ls app/target/*.jar | grep -v "original" | head -n1)
          cp "$JAR_FILE" plugin/resources/mokkyBuddyAPI.jar

      # Aggiorna automaticamente la versione del plugin
      - name: Bump plugin version
        working-directory: plugin
        run: npm version patch --no-git-tag-version

      # Commit e push della nuova versione
      - name: Commit and push version bump
        working-directory: plugin
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json
          git commit -m "Bump plugin version [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build VSCode Plugin
      - name: Build VSCode Plugin
        working-directory: plugin
        run: |
          npm install
          npx vsce package

      # Upload artifact
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mokkybuddy-vscode-plugin
          path: plugin/*.vsix

      # Pubblicazione su Marketplace (opzionale)
      # - name: Publish VSCode Plugin
      #   if: github.ref == 'refs/heads/main'
      #   working-directory: plugin
      #   run: npx vsce publish
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}
