name: Build & Pre-release MokkyBuddy VSCode Plugin
permissions:
  contents: write
  pull-requests: write

on:
  repository_dispatch:
    types: [trigger-plugin-pre-release-build]
  push:
    branches:
      - 'features/**'
      - 'feature/**'

jobs:
  build-and-pre-release:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout plugin e Java App ---
      - name: Checkout Plugin Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.vscode.mokkybuddy
          token: ${{ secrets.GITHUB_TOKEN }}
          path: plugin
          fetch-depth: 0

      - name: Checkout Java App Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.api.mokkybuddy
          ref: ${{ github.event.client_payload.branch || 'main' }}
          token: ${{ secrets.JAVA_APP_PAT }}
          path: app
          fetch-depth: 0

      # --- Setup Node ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # --- Recupero versione Java App ---
      - name: Get Java App version
        id: get_java_version
        run: |
          VERSION=$(mvn -f app/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
          VERSION_CLEAN=${VERSION/-SNAPSHOT/}
          echo "java_version_clean=$VERSION_CLEAN" >> $GITHUB_OUTPUT

      # --- Download JAR ---
      - name: Download JAR artifact from Java App release
        env:
          JAVA_APP_PAT: ${{ secrets.JAVA_APP_PAT }}
          VERSION: ${{ steps.get_java_version.outputs.java_version_clean }}
        run: |
          REPO="stapeDev/it.stapedev.api.mokkybuddy"
          TARGET_DIR=plugin/resources
          TARGET_FILE=$TARGET_DIR/mokkyBuddyAPI.jar
          mkdir -p $TARGET_DIR

          RELEASE_ID=$(curl -s -H "Authorization: token $JAVA_APP_PAT" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/tags/v$VERSION" \
            | jq -r '.id')

          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" == "null" ]; then
            echo "Release not found!"
            exit 1
          fi

          ASSET_URL=$(curl -s -H "Authorization: token $JAVA_APP_PAT" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/$RELEASE_ID/assets" \
            | jq -r '.[] | select(.name | endswith(".jar")) | .url')

          curl -L -H "Authorization: token $JAVA_APP_PAT" \
            -H "Accept: application/octet-stream" \
            "$ASSET_URL" -o "$TARGET_FILE"

      # --- Installa dipendenze e test ---
      - name: Install dependencies
        working-directory: plugin
        run: npm install

      - name: Run tests
        working-directory: plugin
        run: npm test

      # --- Aggiorna versione plugin basata su commit e Java App ---
      - name: Update plugin version based on commits
        working-directory: plugin
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          JAVA_VERSION=${{ steps.get_java_version.outputs.java_version_clean }}
          EXTENSION_ID=$(jq -r '.publisher + "." + .name' package.json)

          # Recupera i commit dall'ultimo tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          RANGE=${LAST_TAG:+$LAST_TAG..HEAD}
          COMMITS=$(git log $RANGE --pretty=format:"%s%b" || true)

          echo "Commits to analyze:"
          echo "$COMMITS"

          # Funzione per confronto semantico
          semver_gt() {
            [ "$(printf '%s\n' "$1" "$2" | sort -V | tail -n1)" = "$1" ]
          }

          # Determina tipo di bump
          if echo "$COMMITS" | grep -q 'BREAKING CHANGE'; then
            echo "BREAKING CHANGE trovata, incremento MAJOR"
            npm version major --no-git-tag-version
          elif echo "$COMMITS" | grep -q '^feat'; then
            echo "Commits feature trovati, incremento MINOR"
            npm version minor --no-git-tag-version
          elif echo "$COMMITS" | grep -q '^fix'; then
            echo "Commits fix trovati, incremento PATCH"
            npm version patch --no-git-tag-version
          else
            if semver_gt "$JAVA_VERSION" "$CURRENT_VERSION"; then
              echo "Allineiamo alla versione Java App $JAVA_VERSION"
              npm version $JAVA_VERSION --no-git-tag-version
            else
              echo "Incrementiamo PATCH di default"
              npm version patch --no-git-tag-version
            fi
          fi

          # Aggiorna vss-extension.json se presente
          if [ -f vss-extension.json ]; then
            jq --arg v "$(jq -r '.version' package.json)" '.version=$v' vss-extension.json > vss-extension.tmp.json
            mv vss-extension.tmp.json vss-extension.json
          fi

      # --- Aggiorna README, CHANGELOG e FEATURES ---
      - name: Update docs
        working-directory: plugin
        run: |
          VERSION=$(jq -r '.version' package.json)
          sed -i "s/badge\/version-[0-9]\+\.[0-9]\+\.[0-9]\+/badge\/version-$VERSION/" README.md || true

          cd ../app
          git fetch --tags --prune || true
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          RANGE=${LAST_TAG:+$LAST_TAG..HEAD}
          FEATS=$(git log $RANGE --grep '^feat' --pretty=format:"- %s (%an)" --reverse || true)
          FIXES=$(git log $RANGE --grep '^fix' --pretty=format:"- %s (%an)" --reverse || true)
          CHORES=$(git log $RANGE --grep '^chore' --pretty=format:"- %s (%an)" --reverse || true)
          BREAKING=$(git log $RANGE --grep 'BREAKING CHANGE' --pretty=format:"- %s (%an)" --reverse || true)
          cd ../plugin

          [ ! -f CHANGELOG.md ] && echo "# Changelog" > CHANGELOG.md
          TMP=$(mktemp)
          echo "## Version $VERSION ($(date +'%Y-%m-%d'))" >> "$TMP"
          [ -n "$FEATS" ] && echo -e "\n### Features\n$FEATS" >> "$TMP"
          [ -n "$FIXES" ] && echo -e "\n### Fixes\n$FIXES" >> "$TMP"
          [ -n "$CHORES" ] && echo -e "\n### Chores\n$CHORES" >> "$TMP"
          [ -n "$BREAKING" ] && echo -e "\n### BREAKING CHANGES\n$BREAKING" >> "$TMP"
          cat "$TMP" CHANGELOG.md > CHANGELOG.new
          mv CHANGELOG.new CHANGELOG.md
          rm -f "$TMP"

      # --- Imposta VERSION come output ---
      - name: Set VERSION output
        id: set_version
        run: |
          VERSION=$(jq -r '.version' plugin/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # --- Commit e pre-release ---
      - name: Commit updates on current branch
        working-directory: plugin
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          CURRENT_BRANCH=${GITHUB_REF_NAME}
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update plugin version, docs, resources [skip ci]" || echo "No changes to commit"
            git push origin "$CURRENT_BRANCH" --force
          fi

      # --- Crea branch pre-release ---
      - name: Create pre-release branch
        working-directory: plugin
        run: |
          VERSION=${{ steps.set_version.outputs.version }}
          CURRENT_BRANCH=${GITHUB_REF_NAME}
          git fetch origin $CURRENT_BRANCH
          git checkout -B pre-release/$VERSION origin/$CURRENT_BRANCH
          git push origin pre-release/$VERSION --force-with-lease

      # --- Crea tag pre-release ---
      - name: Create pre-release tag
        working-directory: plugin
        run: |
          VERSION=${{ steps.set_version.outputs.version }}
          git tag -fa v$VERSION-pre -m "Pre-release $VERSION"
          git push origin v$VERSION-pre --force

      # --- Pubblica plugin come pre-release su VSCode Marketplace ---
      - name: Publish VSCode Plugin as pre-release
        working-directory: plugin
        run: npx @vscode/vsce publish --pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # --- Crea PR da pre-release verso main ---
      - name: Create PR to main
        run: |
          VERSION=${{ steps.set_version.outputs.version }}
          if gh pr list --base main --head pre-release/$VERSION --json number --jq '.[0].number' | grep -q .; then
            echo "PR da pre-release/$VERSION a main esiste già, skip."
          else
            gh pr create \
              --base main \
              --head pre-release/$VERSION \
              --title "PR from pre-release/$VERSION to main." \
              --body "Automated pre-release PR from pre-release/$VERSION to main."
        env:
          GH_TOKEN: ${{ secrets.INTERNAL_PLUGIN_CREATE_PR_PAT }}
          GH_REPO: stapeDev/it.stapedev.vscode.mokkybuddy
