name: Pre-release MokkyBuddy VSCode Plugin

on:
  repository_dispatch:
    types: [trigger-pre-release-plugin-build]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download plugin artifact from build
        uses: actions/download-artifact@v4
        with:
          name: plugin-final
          path: plugin

      - name: Checkout Plugin Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.branch }}
          path: plugin-repo

      - name: Create pre-release branch
        run: |
          VERSION=$(jq -r '.version' plugin/package.json)
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b pre-release/$VERSION
          cp -R ../plugin/* ./plugin-repo/
          git add -A
          git commit -m "Prepare pre-release $VERSION [skip ci]"
          git push origin pre-release/$VERSION --force

      - name: Create pre-release tag
        run: |
          VERSION=$(jq -r '.version' plugin/package.json)
          git tag -fa v$VERSION-pre -m "Pre-release $VERSION"
          git push origin v$VERSION-pre --force

      - name: Publish VSCode Plugin as pre-release
        working-directory: plugin
        run: npx @vscode/vsce publish --pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create PR to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: pre-release/${{ github.event.workflow_run.head_branch }}
          title: "Pre-release ${{ github.event.workflow_run.head_branch }}"
          body: "This is an automated pre-release PR."
