name: Build & Pre-release MokkyBuddy VSCode Plugin
permissions:
  contents: write
  pull-requests: write

on:
  repository_dispatch:
    types: [trigger-plugin-pre-release-build]
  push:
    branches:
      - 'features/**'
      - 'feature/**'

jobs:
  build-and-pre-release:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout plugin e Java App ---
      - name: Checkout Plugin Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.vscode.mokkybuddy
          token: ${{ secrets.GITHUB_TOKEN }}
          path: plugin
          fetch-depth: 0

      - name: Checkout Java App Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.api.mokkybuddy
          ref: ${{ github.event.client_payload.branch || 'main' }}
          token: ${{ secrets.JAVA_APP_PAT }}
          path: app
          fetch-depth: 0

      # --- Setup Node ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # --- Recupero versione Java App ---
      - name: Get Java App version
        id: get_java_version
        run: |
          VERSION=$(mvn -f app/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
          VERSION_CLEAN=${VERSION/-SNAPSHOT/}
          echo "java_version_clean=$VERSION_CLEAN" >> $GITHUB_OUTPUT

      # --- Download JAR (come prima) ---
      - name: Download JAR artifact from Java App release
        env:
          JAVA_APP_PAT: ${{ secrets.JAVA_APP_PAT }}
          VERSION: ${{ steps.get_java_version.outputs.java_version_clean }}
        run: |
          REPO="stapeDev/it.stapedev.api.mokkybuddy"
          TARGET_DIR=plugin/resources
          TARGET_FILE=$TARGET_DIR/mokkyBuddyAPI.jar
          mkdir -p $TARGET_DIR

          RELEASE_ID=$(curl -s -H "Authorization: token $JAVA_APP_PAT" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/tags/v$VERSION" \
            | jq -r '.id')

          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" == "null" ]; then
            echo "Release not found!"
            exit 1
          fi

          ASSET_URL=$(curl -s -H "Authorization: token $JAVA_APP_PAT" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/$RELEASE_ID/assets" \
            | jq -r '.[] | select(.name | endswith(".jar")) | .url')

          curl -L -H "Authorization: token $JAVA_APP_PAT" \
            -H "Accept: application/octet-stream" \
            "$ASSET_URL" -o "$TARGET_FILE"

      # --- Installa dipendenze e test ---
      - name: Install dependencies
        working-directory: plugin
        run: npm install

      - name: Run tests
        working-directory: plugin
        run: npm test

      # --- Aggiorna versione plugin basata su commit e Java App (stessa logica) ---
      - name: Update plugin version based on commits
        working-directory: plugin
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          JAVA_VERSION=${{ steps.get_java_version.outputs.java_version_clean }}
          EXTENSION_ID=$(jq -r '.publisher + "." + .name' package.json)

          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          RANGE=${LAST_TAG:+$LAST_TAG..HEAD}
          COMMITS=$(git log $RANGE --pretty=format:"%s%b" || true)

          echo "Commits to analyze:"
          echo "$COMMITS"

          semver_gt() {
            [ "$(printf '%s\n' "$1" "$2" | sort -V | tail -n1)" = "$1" ]
          }

          if echo "$COMMITS" | grep -q 'BREAKING CHANGE'; then
            echo "BREAKING CHANGE trovata, incremento MAJOR"
            npm version major --no-git-tag-version
          elif echo "$COMMITS" | grep -q '^feat'; then
            echo "Commits feature trovati, incremento MINOR"
            npm version minor --no-git-tag-version
          elif echo "$COMMITS" | grep -q '^fix'; then
            echo "Commits fix trovati, incremento PATCH"
            npm version patch --no-git-tag-version
          else
            if semver_gt "$JAVA_VERSION" "$CURRENT_VERSION"; then
              echo "Allineiamo alla versione Java App $JAVA_VERSION"
              npm version $JAVA_VERSION --no-git-tag-version
            else
              echo "Incrementiamo PATCH di default"
              npm version patch --no-git-tag-version
            fi
          fi

          if [ -f vss-extension.json ]; then
            jq --arg v "$(jq -r '.version' package.json)" '.version=$v' vss-extension.json > vss-extension.tmp.json
            mv vss-extension.tmp.json vss-extension.json
          fi

      # --- Compute base and alpha versions (alpha = base + "-alpha") ---  # <<< NEW >>>
      - name: Compute base and alpha versions
        id: compute_versions
        working-directory: plugin
        run: |
          BASE_VERSION=$(jq -r '.version' package.json)
          ALPHA_VERSION="${BASE_VERSION}-alpha"
          echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT
          echo "alpha_version=$ALPHA_VERSION" >> $GITHUB_OUTPUT
          echo "Computed BASE_VERSION=$BASE_VERSION and ALPHA_VERSION=$ALPHA_VERSION"

      # --- Apply alpha version to package.json and vss-extension.json ---  # <<< NEW >>>
      - name: Apply alpha version
        working-directory: plugin
        run: |
          ALPHA_VERSION=${{ steps.compute_versions.outputs.alpha_version }}
          echo "Applying alpha version: $ALPHA_VERSION"
          # Use npm to set version (no tag)
          npm version "$ALPHA_VERSION" --no-git-tag-version
          if [ -f vss-extension.json ]; then
            jq --arg v "$ALPHA_VERSION" '.version=$v' vss-extension.json > vss-extension.tmp.json
            mv vss-extension.tmp.json vss-extension.json
          fi

      # --- Update docs (use alpha version for badges) ---
      - name: Update docs
        working-directory: plugin
        run: |
          VERSION=${{ steps.compute_versions.outputs.alpha_version }}
          sed -i "s/badge\/version-[0-9]\+\.[0-9]\+\.[0-9]\+/badge\/version-$VERSION/" README.md || true

          cd ../app
          git fetch --tags --prune || true
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          RANGE=${LAST_TAG:+$LAST_TAG..HEAD}
          FEATS=$(git log $RANGE --grep '^feat' --pretty=format:"- %s (%an)" --reverse || true)
          FIXES=$(git log $RANGE --grep '^fix' --pretty=format:"- %s (%an)" --reverse || true)
          CHORES=$(git log $RANGE --grep '^chore' --pretty=format:"- %s (%an)" --reverse || true)
          BREAKING=$(git log $RANGE --grep 'BREAKING CHANGE' --pretty=format:"- %s (%an)" --reverse || true)
          cd ../plugin

          [ ! -f CHANGELOG.md ] && echo "# Changelog" > CHANGELOG.md
          TMP=$(mktemp)
          echo "## Version ${VERSION} ($(date +'%Y-%m-%d'))" >> "$TMP"
          [ -n "$FEATS" ] && echo -e "\n### Features\n$FEATS" >> "$TMP"
          [ -n "$FIXES" ] && echo -e "\n### Fixes\n$FIXES" >> "$TMP"
          [ -n "$CHORES" ] && echo -e "\n### Chores\n$CHORES" >> "$TMP"
          [ -n "$BREAKING" ] && echo -e "\n### BREAKING CHANGES\n$BREAKING" >> "$TMP"
          cat "$TMP" CHANGELOG.md > CHANGELOG.new
          mv CHANGELOG.new CHANGELOG.md
          rm -f "$TMP"

      # --- Set VERSION output (alpha) and BASE output ---  # <<< NEW >>>
      - name: Set VERSION output
        id: set_version
        run: |
          echo "version=${{ steps.compute_versions.outputs.alpha_version }}" >> $GITHUB_OUTPUT
          echo "base_version=${{ steps.compute_versions.outputs.base_version }}" >> $GITHUB_OUTPUT

      # --- Commit alpha version on current branch ---
      - name: Commit alpha version
        working-directory: plugin
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          CURRENT_BRANCH=${GITHUB_REF_NAME}
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Set pre-release alpha version ${ { steps.compute_versions.outputs.alpha_version } } [skip ci]" || echo "No changes to commit"
          else
            echo "No changes to commit"
          fi
          # Push commit to the source branch
          git push origin HEAD || true

      # --- Create pre-release tag (tag is the alpha version) ---
      - name: Create pre-release tag
        working-directory: plugin
        run: |
          VERSION=${{ steps.compute_versions.outputs.alpha_version }}
          TAG=v$VERSION
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG exists, forcing update"
            git tag -f $TAG -m "Pre-release $VERSION"
          else
            git tag -a $TAG -m "Pre-release $VERSION"
          fi
          git push origin $TAG --force

      # --- Zip plugin artifact (alpha) ---
      - name: Zip plugin artifact
        working-directory: plugin
        run: |
          VERSION=${{ steps.compute_versions.outputs.alpha_version }}
          ZIP=plugin-$VERSION.zip
          cd plugin
          zip -r ../$ZIP .
          cd ..

      # --- Create GitHub pre-release and upload asset (alpha) ---
      - name: Create GitHub pre-release and upload asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: stapeDev/it.stapedev.vscode.mokkybuddy
          VERSION: ${{ steps.compute_versions.outputs.alpha_version }}
        run: |
          TAG=v${VERSION}
          PAYLOAD=$(jq -n --arg tag "$TAG" --arg name "$TAG" --arg body "Pre-release $VERSION" '{"tag_name":$tag,"name":$name,"body":$body,"prerelease":true}')
          echo "$PAYLOAD" > /tmp/release_payload.json

          # Create release
          RESP=$(curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases" -d @/tmp/release_payload.json)

          UPLOAD_URL=$(echo "$RESP" | jq -r '.upload_url')
          if [ -z "$UPLOAD_URL" ] || [ "$UPLOAD_URL" = "null" ]; then
            echo "Failed to create release. Response:"
            echo "$RESP"
            exit 1
          fi

          ZIP=plugin-${VERSION}.zip
          UPLOAD_URL_EXPANDED="${UPLOAD_URL%\{*}?name=$ZIP"
          echo "Uploading $ZIP to $UPLOAD_URL_EXPANDED"
          curl -s --data-binary @"$ZIP" \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/zip" \
              "$UPLOAD_URL_EXPANDED" | jq -r '.browser_download_url'

      # --- Publish plugin as pre-release to VSCode Marketplace ---
      - name: Publish VSCode Plugin as pre-release
        working-directory: plugin
        run: |
          npm install  # ensure dependencies like typescript are available for package scripts
          npx @vscode/vsce publish --pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # --- Create pre-release branch containing base (clean) version ---
      - name: Create pre-release branch with base version
        working-directory: plugin
        run: |
          BASE_VERSION=${{ steps.compute_versions.outputs.base_version }}
          CURRENT_BRANCH=${GITHUB_REF_NAME}
          git fetch origin $CURRENT_BRANCH
          # create branch from origin/current branch
          git checkout -B pre-release/$BASE_VERSION origin/$CURRENT_BRANCH

          # restore base version in new branch
          npm version $BASE_VERSION --no-git-tag-version || true
          if [ -f vss-extension.json ]; then
            jq --arg v "$BASE_VERSION" '.version=$v' vss-extension.json > vss-extension.tmp.json
            mv vss-extension.tmp.json vss-extension.json
          fi

          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Restore base version $BASE_VERSION for pre-release branch [skip ci]" || echo "No changes to commit"
          fi
          git push origin pre-release/$BASE_VERSION --force-with-lease

      # --- Create PR from pre-release/{base_version} -> main ---
      - name: Create PR to main
        run: |
          VERSION=${{ steps.compute_versions.outputs.base_version }}
          if gh pr list --base main --head pre-release/$VERSION --json number --jq '.[0].number' | grep -q .; then
            echo "PR from pre-release/$VERSION to main already exists, skip."
          else
            gh pr create \
              --base main \
              --head pre-release/$VERSION \
              --title "PR from pre-release/$VERSION to main." \
              --body "Automated pre-release PR from pre-release/$VERSION to main."
          fi
        env:
          GH_TOKEN: ${{ secrets.INTERNAL_PLUGIN_CREATE_PR_PAT }}
          GH_REPO: stapeDev/it.stapedev.vscode.mokkybuddy
