name: Build & Pre-release MokkyBuddy VSCode Plugin

on:
  push:
    branches:
      - 'dependabot/**'
      - 'features/**'
      - 'feature/**'

jobs:
  build-and-pre-release:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout plugin e Java App ---
      - name: Checkout Plugin Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.vscode.mokkybuddy
          token: ${{ secrets.GITHUB_TOKEN }}
          path: plugin

      - name: Checkout Java App Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.api.mokkybuddy
          ref: main
          token: ${{ secrets.JAVA_APP_PAT }}
          path: app
          fetch-depth: 0

      # --- Setup Node ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # --- Recupero versione Java App ---
      - name: Get Java App version
        id: get_java_version
        run: |
          VERSION=$(mvn -f app/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
          VERSION_CLEAN=${VERSION/-SNAPSHOT/}
          echo "java_version_clean=$VERSION_CLEAN" >> $GITHUB_OUTPUT

      # --- Download JAR ---
      - name: Download JAR artifact from Java App release
        env:
          JAVA_APP_PAT: ${{ secrets.JAVA_APP_PAT }}
          VERSION: ${{ steps.get_java_version.outputs.java_version_clean }}
        run: |
          REPO="stapeDev/it.stapedev.api.mokkybuddy"
          TARGET_DIR=plugin/resources
          TARGET_FILE=$TARGET_DIR/mokkyBuddyAPI.jar
          mkdir -p $TARGET_DIR

          RELEASE_ID=$(curl -s -H "Authorization: token $JAVA_APP_PAT" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/tags/v$VERSION" \
            | jq -r '.id')

          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" == "null" ]; then
            echo "Release not found!"
            exit 1
          fi

          ASSET_URL=$(curl -s -H "Authorization: token $JAVA_APP_PAT" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/$RELEASE_ID/assets" \
            | jq -r '.[] | select(.name | endswith(".jar")) | .url')

          curl -L -H "Authorization: token $JAVA_APP_PAT" \
            -H "Accept: application/octet-stream" \
            "$ASSET_URL" -o "$TARGET_FILE"

      # --- Installa dipendenze e test ---
      - name: Install dependencies
        working-directory: plugin
        run: npm install

      - name: Run tests
        working-directory: plugin
        run: npm test

      # --- Aggiorna versione plugin e file JSON ---
      - name: Update plugin version to Java app version
        working-directory: plugin
        run: |
          JAVA_VERSION=${{ steps.get_java_version.outputs.java_version_clean }}
          CURRENT_VERSION=$(jq -r '.version' package.json)

          # Controllo se la versione esiste già sul marketplace
          EXTENSION_ID=$(jq -r '.publisher + "." + .name' package.json)
          if npx vsce show $EXTENSION_ID@$JAVA_VERSION > /dev/null 2>&1; then
            echo "Version $JAVA_VERSION already published, bumping patch"
            npm version patch --no-git-tag-version
          else
            echo "Using Java version $JAVA_VERSION"
            npm version $JAVA_VERSION --no-git-tag-version
          fi

          # Aggiorna vss-extension.json se presente
          if [ -f vss-extension.json ]; then
            jq --arg v "$(jq -r '.version' package.json)" '.version=$v' vss-extension.json > vss-extension.tmp.json
            mv vss-extension.tmp.json vss-extension.json
          fi

      # --- Aggiorna README, CHANGELOG e FEATURES ---
      - name: Update docs
        working-directory: plugin
        run: |
          VERSION=$(jq -r '.version' package.json)
          sed -i "s/badge\/version-[0-9]\+\.[0-9]\+\.[0-9]\+/badge\/version-$VERSION/" README.md || true

          cd ../app
          git fetch --tags --prune || true
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          RANGE=${LAST_TAG:+$LAST_TAG..HEAD}
          FEATS=$(git log $RANGE --grep '^feat' --pretty=format:"- %s (%an)" --reverse || true)
          FIXES=$(git log $RANGE --grep '^fix' --pretty=format:"- %s (%an)" --reverse || true)
          CHORES=$(git log $RANGE --grep '^chore' --pretty=format:"- %s (%an)" --reverse || true)
          BREAKING=$(git log $RANGE --grep 'BREAKING CHANGE' --pretty=format:"- %s (%an)" --reverse || true)
          cd ../plugin

          [ ! -f CHANGELOG.md ] && echo "# Changelog" > CHANGELOG.md
          TMP=$(mktemp)
          echo "## Version $VERSION ($(date +'%Y-%m-%d'))" >> "$TMP"
          [ -n "$FEATS" ] && echo -e "\n### Features\n$FEATS" >> "$TMP"
          [ -n "$FIXES" ] && echo -e "\n### Fixes\n$FIXES" >> "$TMP"
          [ -n "$CHORES" ] && echo -e "\n### Chores\n$CHORES" >> "$TMP"
          [ -n "$BREAKING" ] && echo -e "\n### BREAKING CHANGES\n$BREAKING" >> "$TMP"
          cat "$TMP" CHANGELOG.md > CHANGELOG.new
          mv CHANGELOG.new CHANGELOG.md
          rm -f "$TMP"

      # --- Commit su branch pre-release ---
      - name: Commit pre-release branch
        working-directory: plugin
        run: |
          VERSION=$(jq -r '.version' package.json)
          BRANCH="pre-release/$VERSION"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b $BRANCH || git checkout $BRANCH
          git add -A
          git commit -m "Prepare pre-release $VERSION [skip ci]" || echo "No changes to commit"
          git push origin $BRANCH --force

      # --- Crea tag pre-release ---
      - name: Create pre-release tag
        working-directory: plugin
        run: |
          VERSION=$(jq -r '.version' package.json)
          git tag -fa v$VERSION-pre -m "Pre-release $VERSION"
          git push origin v$VERSION-pre --force

      # --- Build VSIX ---
      - name: Build VSCode Plugin (.vsix)
        working-directory: plugin
        run: npx vsce package

      # --- Pubblica pre-release su VSCE ---
      - name: Publish VSCode Plugin as pre-release
        working-directory: plugin
        run: npx @vscode/vsce publish --pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Checkout plugin repo for PR
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: plugin-repo
          fetch-depth: 0

      - name: Create PR to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: pre-release/${{ steps.get_version.outputs.version }}
          title: "Pre-release ${{ steps.get_version.outputs.version }}"
          body: "This is an automated pre-release PR."
          path: plugin-repo
