name: Release MokkyBuddy VSCode Plugin
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release:
  runs-on: ubuntu-latest
  needs: versioning
  steps:
    # Checkout plugin con path
    - uses: actions/checkout@v3
      with:
        path: plugin
        fetch-depth: 0

    # Configura git
    - name: Setup Git
      run: |
        cd plugin
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    # Crea branch di release stabile
    - name: Create release branch
      run: |
        cd plugin
        RELEASE_VERSION=${{ needs.versioning.outputs.release_version }}
        git checkout -b release/$RELEASE_VERSION
        git push origin release/$RELEASE_VERSION

    # Crea tag stabile
    - name: Tag release
      run: |
        cd plugin
        RELEASE_VERSION=${{ needs.versioning.outputs.release_version }}
        git tag -a "v$RELEASE_VERSION" -m "Release $RELEASE_VERSION"
        git push origin "v$RELEASE_VERSION"

    # Publish su Marketplace
    - name: Publish stable release
      run: |
        cd plugin
        npx @vscode/vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
