name: Release MokkyBuddy VSCode Plugin
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout plugin
      - uses: actions/checkout@v3
        with:
          path: plugin
          fetch-depth: 0

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Recupera versione finale dal package.json (post pre-release)
      - name: Set release version
        id: set_release_version
        run: |
          cd plugin
          PRE_VERSION=$(jq -r '.version' package.json)
          RELEASE_VERSION=${PRE_VERSION/-pre/}
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "Release version: $RELEASE_VERSION"

      # Create release branch
      - name: Create release branch
        run: |
          cd plugin
          RELEASE_VERSION=${{ steps.set_release_version.outputs.release_version }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B release/$RELEASE_VERSION
          git push origin release/$RELEASE_VERSION --force-with-lease

      # Create release tag
      - name: Create release tag
        run: |
          cd plugin
          RELEASE_VERSION=${{ steps.set_release_version.outputs.release_version }}
          TAG=v$RELEASE_VERSION
          git tag -a "$TAG" -m "Release $RELEASE_VERSION"
          git push origin "$TAG" --force

      # Publish release su Marketplace
      - name: Publish Marketplace
        run: |
          cd plugin
          npm ci
          npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
