name: Release MokkyBuddy VSCode Plugin
permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout plugin repo ---
      - name: Checkout Plugin Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.vscode.mokkybuddy
          token: ${{ secrets.GITHUB_TOKEN }}
          path: plugin-repo

      # --- Find last successful pre-release run and download artifact ---
      - name: Download latest pre-release artifact
        run: |
          echo "Fetching last successful pre-release run..."
          LATEST_RUN_ID=$(gh run list \
            --workflow "Build & Pre-release MokkyBuddy VSCode Plugin" \
            --branch $(git rev-parse --abbrev-ref HEAD) \
            --status success \
            --json databaseId \
            --jq '.[0].databaseId')

          if [ -z "$LATEST_RUN_ID" ]; then
            echo "No successful pre-release run found. Exiting."
            exit 1
          fi

          echo "Latest run ID: $LATEST_RUN_ID"
          gh run download $LATEST_RUN_ID --name plugin-final --dir plugin-artifact

      # --- Copy artifact into repo ---
      - name: Copy artifact into repo
        run: |
          cp -R plugin-artifact/* plugin-repo/
          cd plugin-repo
          git add -A

      # --- Determine plugin version ---
      - name: Determine plugin version
        id: version
        run: |
          cd plugin-repo
          VERSION=$(jq -r '.version' package.json)
          if [ -z "$VERSION" ]; then
            echo "Version is empty! Exiting."
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # --- Create release branch ---
      - name: Create release branch
        run: |
          cd plugin-repo
          RELEASE_BRANCH=release/${{ steps.version.outputs.version }}
          if git show-ref --verify --quiet refs/heads/$RELEASE_BRANCH; then
            echo "Branch $RELEASE_BRANCH already exists, using existing branch"
            git checkout $RELEASE_BRANCH
          else
            git checkout -b $RELEASE_BRANCH
          fi
          if ! git diff --cached --quiet; then
            git commit -m "Prepare release ${{ steps.version.outputs.version }} [skip ci]"
            git push origin $RELEASE_BRANCH
          fi

      # --- Create release tag ---
      - name: Create release tag
        run: |
          cd plugin-repo
          TAG=v${{ steps.version.outputs.version }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping creation"
          else
            git tag -a $TAG -m "Release $TAG"
            git push origin $TAG
          fi

      # --- Publish VSCode Plugin as release ---
      - name: Publish VSCode Plugin as release
        working-directory: plugin-repo
        run: npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
