name: Release MokkyBuddy VSCode Plugin
permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout repo ---
      - name: Checkout Plugin Repo
        uses: actions/checkout@v3
        with:
          repository: stapeDev/it.stapedev.vscode.mokkybuddy
          token: ${{ secrets.GITHUB_TOKEN }}
          path: plugin-repo

      # --- Read version from repository (main) ---
      - name: Read plugin version
        id: version
        run: |
          VERSION=$(jq -r '.version' plugin-repo/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # --- Download pre-release asset from GitHub Release (NEW) ---
      - name: Download pre-release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: stapeDev/it.stapedev.vscode.mokkybuddy
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          TAG=v${VERSION}-pre
          echo "Fetching release for tag $TAG"
          RESP=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/tags/$TAG")

          ASSET_URL=$(echo "$RESP" | jq -r '.assets[] | select(.name | endswith(".zip")) | .url' )
          if [ -z "$ASSET_URL" ] || [ "$ASSET_URL" = "null" ]; then
            echo "Asset not found for tag $TAG. Response:"
            echo "$RESP"
            exit 1
          fi

          FNAME=plugin-${VERSION}.zip
          echo "Downloading asset $FNAME"
          curl -L -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/octet-stream" \
            "$ASSET_URL" -o "$FNAME"

          mkdir -p plugin-artifact
          unzip -o "$FNAME" -d plugin-artifact

      # --- Leggi versione dal package.json dentro l'artifact (stessa logica, ora dal repo) ---
      - name: Read plugin version (artifact fallback)
        id: version_artifact
        run: |
          if [ -f plugin-artifact/package.json ]; then
            VERSION_ARTIFACT=$(jq -r '.version' plugin-artifact/package.json)
            echo "version_artifact=$VERSION_ARTIFACT" >> $GITHUB_OUTPUT
          else
            echo "version_artifact=" >> $GITHUB_OUTPUT
          fi

      # --- Copia artifact nella repo ---
      - name: Copy artifact into repo
        run: |
          cp -R plugin-artifact/* plugin-repo/
          cd plugin-repo
          git add -A

      # --- Crea branch release ---
      - name: Create release branch
        run: |
          cd plugin-repo
          RELEASE_BRANCH=release/${{ steps.version.outputs.version }}
          if git show-ref --verify --quiet refs/heads/$RELEASE_BRANCH; then
            git checkout $RELEASE_BRANCH
          else
            git checkout -b $RELEASE_BRANCH
          fi
          if ! git diff --cached --quiet; then
            git commit -m "Prepare release ${{ steps.version.outputs.version }} [skip ci]"
            git push origin $RELEASE_BRANCH
          fi

      # --- Crea tag release ---
      - name: Create release tag
        run: |
          cd plugin-repo
          TAG=v${{ steps.version.outputs.version }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already esiste, skip"
          else
            git tag -a $TAG -m "Release $TAG"
            git push origin $TAG
          fi

      # --- Pubblica plugin sul Marketplace ---
      - name: Publish VSCode Plugin as release
        working-directory: plugin-repo
        run: npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
