name: Release MokkyBuddy VSCode Plugin
permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # --- Scarica l'artefatto di build dalla pipeline di pre-release ---
      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix-artifact

      - name: Get tag version
        id: version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "artifact_version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Setup Node for vsce
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # --- Pubblica il plugin su VSCode Marketplace ---
      - name: Publish VSCode Plugin as release
        run: |
          ls -la
          npx @vscode/vsce publish --packagePath *.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # --- Crea la release su GitHub ---
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.version.outputs.artifact_version }}
          draft: false
          prerelease: false
          files: '*.vsix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}