name: Release MokkyBuddy VSCode Plugin
permissions:
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout repo principale ---
      - name: Checkout Plugin Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # --- Configure Git identity ---
      - name: Configure Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # --- Fetch latest pre-release tag and derive ARTIFACT_VERSION (fallback) ---
      - name: Get latest pre-release version
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: stapeDev/it.stapedev.vscode.mokkybuddy
        run: |
          LATEST_PRERELEASE_TAG=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases" \
            | jq -r '.[] | select(.prerelease==true) | .tag_name' | sort -V | tail -n1)

          if [ -z "$LATEST_PRERELEASE_TAG" ] || [ "$LATEST_PRERELEASE_TAG" = "null" ]; then
            echo "No pre-release found!"
            exit 1
          fi

          ARTIFACT_VERSION="${LATEST_PRERELEASE_TAG#v}"
          ARTIFACT_VERSION="${ARTIFACT_VERSION%-pre}"

          echo "artifact_version=$ARTIFACT_VERSION" >> $GITHUB_OUTPUT
          echo "latest_prerelease_tag=$LATEST_PRERELEASE_TAG" >> $GITHUB_OUTPUT
          echo "Found latest pre-release tag: $LATEST_PRERELEASE_TAG -> artifact_version=$ARTIFACT_VERSION"

      # --- Download pre-release asset ---
      - name: Download pre-release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: stapeDev/it.stapedev.vscode.mokkybuddy
          ARTIFACT_VERSION: ${{ steps.version.outputs.artifact_version }}
        run: |
          VERSION=${ARTIFACT_VERSION}
          LATEST_TAG=v${VERSION}-pre
          echo "Fetching release for tag $LATEST_TAG"
          RESP=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/releases/tags/$LATEST_TAG")

          ASSET_URL=$(echo "$RESP" | jq -r '.assets[] | select(.name | endswith(".zip")) | .browser_download_url' || true)
          if [ -z "$ASSET_URL" ] || [ "$ASSET_URL" = "null" ]; then
            echo "Asset not found for tag $LATEST_TAG. Response:"
            echo "$RESP"
            exit 1
          fi

          FNAME=plugin-${VERSION}.zip
          echo "Downloading asset $FNAME from $ASSET_URL"
          curl -L -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/octet-stream" \
            "$ASSET_URL" -o "$FNAME"

          mkdir -p plugin-artifact
          unzip -o "$FNAME" -d plugin-artifact
          echo "Unzipped artifact into plugin-artifact/"

      # --- Read plugin version (artifact fallback) ---
      - name: Read plugin version
        id: version_artifact
        run: |
          if [ -f plugin-artifact/package.json ]; then
            VERSION_ARTIFACT=$(jq -r '.version' plugin-artifact/package.json)
            echo "version_artifact=$VERSION_ARTIFACT" >> $GITHUB_OUTPUT
          else
            echo "version_artifact=" >> $GITHUB_OUTPUT
          fi

      # --- Copy artifact into repo (robusto, evita errori "non-empty directory") ---
      - name: Copy artifact into repo
        run: |
          set -euo pipefail

          # prepara una cartella temporanea isolata e copia lì il contenuto dell'artifact
          TMPDIR=$(mktemp -d)
          echo "Using temporary dir: $TMPDIR"
          rsync -a plugin-artifact/ "$TMPDIR"/

          # poi sincronizza dalla temp dir alla root del repo (evita conflitti con plugin-artifact/)
          rsync -av --delete-after \
            --exclude 'package.json' \
            --exclude 'vss-extension.json' \
            --exclude 'node_modules' \
            "$TMPDIR"/ .

          RSYNC_EXIT=$?
          # pulizia
          rm -rf "$TMPDIR"

          # gestisci exit code di rsync: ignora 24 (warning "some files vanished"), fallisci per altri codici
          if [ $RSYNC_EXIT -eq 24 ]; then
            echo "rsync returned code 24 (some files vanished) — treating as non-fatal and continuing."
          elif [ $RSYNC_EXIT -ne 0 ]; then
            echo "rsync failed with exit code $RSYNC_EXIT — aborting."
            exit $RSYNC_EXIT
          fi

          # aggiungi modifiche a git
          git add -A || true

      # --- Create release branch (stile pre-release) ---
      - name: Create release branch
        working-directory: .
        run: |
          RELEASE_VERSION=$(jq -r '.version' package.json)
          CURRENT_BRANCH=${GITHUB_REF_NAME}

          git fetch origin $CURRENT_BRANCH
          git checkout -B release/$RELEASE_VERSION origin/$CURRENT_BRANCH

          git add -A
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if ! git diff --cached --quiet; then
            git commit -m "Prepare release $RELEASE_VERSION [skip ci]" || echo "No changes to commit"
          fi

          git push origin release/$RELEASE_VERSION --force-with-lease

      # --- Create release tag ---
      - name: Create release tag
        working-directory: .
        run: |
          RELEASE_VERSION=$(jq -r '.version' package.json)
          TAG=v$RELEASE_VERSION

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            git tag -f "$TAG" -m "Release $RELEASE_VERSION"
          else
            git tag -a "$TAG" -m "Release $RELEASE_VERSION"
          fi

          git push origin "$TAG" --force

      # --- Install Node dependencies ---
      - name: Install Node dependencies
        working-directory: .
        run: npm ci

      # --- Publish plugin to VSCode Marketplace ---
      - name: Publish VSCode Plugin as release
        working-directory: .
        run: |
          PUBLISH_VERSION=$(jq -r '.version' package.json)
          echo "Publishing version from package.json: $PUBLISH_VERSION"
          npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
